In [3]:
"""
Created on 05.08.2022 - 14:34

@author: Ozkan

"""

'\nCreated on 05.08.2022 - 14:34\n\n@author: Ozkan\n\n'

# First import lib's

In [4]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import streamlit as st
from datetime import datetime

# Load Data

In [5]:
df_agg=pd.read_csv('Aggregated_Metrics_By_Video.csv').iloc[1:,:] #droped 0 index its include titles
df_agg.head(4)

,Video,Video title,Video pub­lish time,Com­ments ad­ded,Shares,Dis­likes,Likes,Sub­scribers lost,Sub­scribers gained,RPM (USD),CPM (USD),Av­er­age per­cent­age viewed (%),Av­er­age view dur­a­tion,Views,Watch time (hours),Sub­scribers,Your es­tim­ated rev­en­ue (USD),Im­pres­sions,Im­pres­sions click-through rate (%)
1,4OZip0cgOho,How I Would Learn Data Science (If I Had to St...,"May 8, 2020",907,9583,942,46903,451,46904,6.353,12.835,36.65,0:03:09,1253559,65850.7042,46453,7959.533,26498799,3.14
2,78LjdAAw0wA,100K Channel Update + AMA Stream!,"Nov 12, 2020",412,4,4,130,15,12,2.668,6.259,6.26,0:05:14,2291,200.2966,-3,6.113,188318,0.72
3,hO_YKK_0Qck,Uber Driver to Machine Learning Engineer in 9 ...,"Jul 16, 2020",402,152,15,881,9,198,9.516,11.695,15.12,0:10:21,21350,3687.3387,189,202.963,442334,2.53
4,uXLnbdHMf8w,Why I'm Starting Data Science Over Again.,"Aug 29, 2020",375,367,22,2622,40,1957,3.143,7.943,33.41,0:02:36,49564,2148.3110,1917,155.779,521185,4.01

In [8]:
df_agg.columns=['Video','Video title','Video publish time','Comments added',
               'Shares','Dislikes','Likes','Subscribers Lost','Subscribers gained','RPM(USD)','CPM(USD)','Average % viewed',
               'Average view duration','Views','Watch time (hours)','Subscribers','Your estimated revenue (USD)', 'Impressions','Impressions ctr(%)']

In [9]:
df_agg['Video publish time'].head() #convert to datetime

1     May 8, 2020
2    Nov 12, 2020
3    Jul 16, 2020
4    Aug 29, 2020
5     Aug 5, 2020
Name: Video publish time, dtype: object

In [10]:
df_agg['Video publish time']=pd.to_datetime(df_agg['Video publish time'])

In [11]:
df_agg['Video publish time']

1     2020-05-08
2     2020-11-12
3     2020-07-16
4     2020-08-29
5     2020-08-05
         ...
219   2018-11-30
220   2019-05-25
221   2018-12-18
222   2019-05-05
223   2017-06-06
Name: Video publish time, Length: 223, dtype: datetime64[ns]

In [12]:
df_agg['Average view duration'].head()

1    0:03:09
2    0:05:14
3    0:10:21
4    0:02:36
5    0:04:37
Name: Average view duration, dtype: object

In [13]:
df_agg['Average view duration']=df_agg['Average view duration'].apply(lambda x: datetime.strptime(x,'%H:%M:%S'))

In [14]:
df_agg['Average view duration']

1     1900-01-01 00:03:09
2     1900-01-01 00:05:14
3     1900-01-01 00:10:21
4     1900-01-01 00:02:36
5     1900-01-01 00:04:37
              ...
219   1900-01-01 00:03:28
220   1900-01-01 00:02:06
221   1900-01-01 00:01:52
222   1900-01-01 00:03:09
223   1900-01-01 00:01:04
Name: Average view duration, Length: 223, dtype: datetime64[ns]

In [15]:
df_agg['Average_view_duration_second']=df_agg['Average view duration'].apply(lambda x:x.second + x.minute*60 + x.hour*3600)
df_agg['Average_view_duration_second']

1      189
2      314
3      621
4      156
5      277
      ...
219    208
220    126
221    112
222    189
223     64
Name: Average_view_duration_second, Length: 223, dtype: int64

In [16]:
df_agg['Engaged_ratio']=(df_agg['Comments added']+ df_agg['Shares']+df_agg['Dislikes']+df_agg['Likes']) / df_agg.Views
df_agg['Engaged_ratio']

1      0.046536
2      0.240070
3      0.067916
4      0.068316
5      0.078338
         ...
219    0.058282
220    0.085766
221    0.054092
222    0.041133
223    0.050000
Name: Engaged_ratio, Length: 223, dtype: float64

In [19]:
df_agg['Views / sub gained']=df_agg['Views'] / df_agg['Subscribers gained']
df_agg['Views / sub gained']

1       26.726057
2      190.916667
3      107.828283
4       25.326520
5       83.409938
          ...
219    122.250000
220    109.600000
221    103.000000
222    364.666667
223           inf
Name: Views / sub gained, Length: 223, dtype: float64

In [20]:
df_agg.sort_values('Video publish time',ascending=False,inplace=True)
df_agg

,Video,Video title,Video publish time,Comments added,Shares,Dislikes,Likes,Subscribers Lost,Subscribers gained,RPM(USD),...,Average view duration,Views,Watch time (hours),Subscribers,Your estimated revenue (USD),Impressions,Impressions ctr(%),Average_view_duration_second,Engaged_ratio,Views / sub gained
111,0jTtHYie3CU,Should You Be Excited About Web 3? (As a Data ...,2022-01-17,37,43,8,267,14,18,4.055,...,1900-01-01 00:02:38,4383,192.5779,4,16.549,65130,2.95,158,0.080995,243.500000
187,2RWwN5ZT4tA,Should @Luke Barousse Take This Data Analyst ...,2022-01-14,12,2,3,78,1,1,1.882,...,1900-01-01 00:00:38,2401,25.9375,0,1.720,25094,2.64,38,0.039567,2401.000000
64,rEWPqw6rMGI,The Only Data Science Explanation You Need,2022-01-10,62,141,5,722,28,136,5.971,...,1900-01-01 00:04:40,10277,801.5549,108,60.498,215491,2.22,280,0.090493,75.566176
59,o-wsyxWbPOw,We Need to Talk About The LinkedIn Machine Lea...,2022-01-03,65,36,12,592,10,78,5.321,...,1900-01-01 00:02:46,11808,545.6332,68,62.568,166915,3.32,166,0.059705,151.384615
32,xpIFS6jZbe8,How I Would Learn Data Science in 2022 (If I H...,2021-12-27,109,767,53,4413,46,2553,6.836,...,1900-01-01 00:04:29,79283,5945.5420,2507,528.286,1420968,3.31,269,0.067379,31.054837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,RRSRKf9eQxc,Should You Get A Masters in Data Science?,2018-11-14,56,41,10,276,2,81,7.398,...,1900-01-01 00:02:32,18488,782.5937,79,136.708,173610,8.40,152,0.020716,228.246914
190,IFceyuL6GZY,How I Became A Data Scientist From a Business ...,2018-11-12,11,33,4,168,0,81,4.419,...,1900-01-01 00:03:57,5515,363.4858,81,24.358,58816,5.72,237,0.039166,68.086420
204,Y_SMU701qlA,Predicting Season Long NBA Wins Using Multiple...,2018-07-10,7,45,2,159,1,34,2.883,...,1900-01-01 00:02:25,6863,276.7257,33,19.772,53865,4.03,145,0.031036,201.852941
138,qfRhKHV8-t4,Predicting Crypto-Currency Price Using RNN lST...,2017-11-18,28,114,18,247,1,111,1.326,...,1900-01-01 00:01:45,16558,487.2194,110,21.944,168508,5.65,105,0.024580,149.171171
223,5p73cIRYCZg,ProjectDemoCSC478_UFCFightData,2017-06-06,0,2,0,1,0,0,0.050,...,1900-01-01 00:01:04,60,1.0684,0,0.003,365,11.51,64,0.050000,inf

In [21]:
df_agg_sub=pd.read_csv('Aggregated_Metrics_By_Country_And_Subscriber_Status.csv')

In [22]:
df_comments=pd.read_csv('Aggregated_Metrics_By_Video.csv')

In [24]:
df_time=pd.read_csv('Video_Performance_Over_Time.csv')

In [26]:
df_time.info() #date must be datatime

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111857 entries, 0 to 111856
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        111857 non-null  object
 1   Video Title                 111857 non-null  object
 2   External Video ID           111857 non-null  object
 3   Video Length                111857 non-null  int64
 4   Thumbnail link              111857 non-null  object
 5   Views                       111857 non-null  int64
 6   Video Likes Added           111857 non-null  int64
 7   Video Dislikes Added        111857 non-null  int64
 8   Video Likes Removed         111857 non-null  int64
 9   User Subscriptions Added    111857 non-null  int64
 10  User Subscriptions Removed  111857 non-null  int64
 11  Average View Percentage     110510 non-null  float64
 12  Average Watch Time          110510 non-null  float64
 13  User Comments Added         111857 non-null  int64
dtypes: float64(2), int64(8), object(4)
memory usage: 11.9+ MB

In [27]:
df_time['Date']=pd.to_datetime(df_time['Date'])

# Easy Function

In [30]:
#@st.cache
def load_data():
    df_agg=pd.read_csv('Aggregated_Metrics_By_Video.csv').iloc[1:,:] #droped 0 index its include titles
    df_agg.columns=['Video','Video title','Video publish time','Comments added',
               'Shares','Dislikes','Likes','Subscribers Lost','Subscribers gained','RPM(USD)','CPM(USD)','Average % viewed',
               'Average view duration','Views','Watch time (hours)','Subscribers','Your estimated revenue (USD)', 'Impressions','Impressions ctr(%)']
    
    df_agg['Video publish time']=pd.to_datetime(df_agg['Video publish time'])

    df_agg['Average view duration']=df_agg['Average view duration'].apply(lambda x: datetime.strptime(x,'%H:%M:%S'))
    
    df_agg['Average_view_duration_second']=df_agg['Average view duration'].apply(lambda x:x.second + x.minute*60 + x.hour*3600)
    
    df_agg['Engaged_ratio']=(df_agg['Comments added']+ df_agg['Shares']+df_agg['Dislikes']+df_agg['Likes']) / df_agg.Views
    
    df_agg['Views / sub gained']=df_agg['Views'] / df_agg['Subscribers gained']
    

    df_agg.sort_values('Video publish time',ascending=False,inplace=True)
    
    df_agg_sub=pd.read_csv('Aggregated_Metrics_By_Country_And_Subscriber_Status.csv')
    
    df_comments=pd.read_csv('Aggregated_Metrics_By_Video.csv')
    
    df_time=pd.read_csv('Video_Performance_Over_Time.csv')
    
    
    df_time['Date']=pd.to_datetime(df_time['Date'])
    
    return df_agg,df_agg_sub,df_comments,df_time




#create df's from function
df_agg,df_agg_sub,df_comments,df_time=load_data()

# Streamlit need to .py documents so that i cant build with notebook i decided to change with spider